### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by EndangeredNayla** [Craftjakob/Enderite-CJ-Edition#1]

**Comment by Craftjakob** [comment]
Still?

**Comment by Craftjakob** [comment]
Wait, can you say what version of minecraft do you use? Because only 1.19.3 and 1.19.4 have the 0.8.5 Update with the server fix, and I've tested the mod on 1.19.4 and 1.19.3 server.

**Comment by Craftjakob** [comment]
0.8.5 was released maybe half an hour ago. With a Server fix. Currently, for 1.19.3 and 1.19.4. I've tested these version and the server and client have work.

**Comment by EndangeredNayla** [comment]
I use 1.19.2. anything newer is a snapshot

**Comment by Craftjakob** [comment]
Okay, only for you, I will release the 0.8.5 for 1.19 to 1.19.2.
I always release my mods for the 1.19.4 and 1.19.3 because the versions are similar, but for 1.19 to 1.19.2 I need to change more. That's why updates for lower versions don't come that often.

**Comment by Craftjakob** [comment]
I finally uploaded the files. You can maybe download them in 10 to 25 minutes.

**Comment by EndangeredNayla** [comment]
Thank you :)
