### ISSUE TITLE
[Fabric 1.20.6] Damage problem

### ISSUE THREAD

**Issue by V1lo4ka** [Craftjakob/Enderite-CJ-Edition#10]
Hello, 
Started testing your mod. When I was testing tools, tools and sword had practically 0 damage on them, fells like it missing damage attribute or smth.
Tbh I am not exceeding in modding knowledge so I probably poorly explained what happened.

**Comment by Craftjakob** [comment]
Yes the attribute in the Item.Properties is missing, minecraft has change too much for a small update.

My question is should the Damage configured by one config or for every item a config for attack damage.
Becuase it is not only one number that I need to change, there is a "base" and a "bonus".

**Comment by V1lo4ka** [comment]
Imho, it should be one config.
Thank you for fast answer^^

**Comment by Craftjakob** [comment]
I have uploaded the new version, in a few minutes can you download it.
