### ISSUE TITLE
Unable to update previous world

### ISSUE THREAD

**Issue by Basdower** [Craftjakob/Enderite-CJ-Edition#11]
I recently tried using the latest 1.21 and everytime I try to open an older world (1.20.5) the game shows the "lost connection" screen I is unable to load the world. It may be an enchantment issue due to "Missing registry: ResourceKey[minecraft:root / minecraft:enchantment]". I had no problen when creating a new world with the mod installed though

**Comment by Craftjakob** [comment]
Yip, I am going to upload a new file, thanks for reporting!
