### ISSUE TITLE
Gilded Enderite Armor uncraftable

### ISSUE THREAD

**Issue by Yenistax** [Craftjakob/Enderite-CJ-Edition#12]
I don't know how to explain to you my problem but the gilded enderite armor cannot be craft but in the JEI, we see the craft.  My minecraft version is 1.21 and the mod version is Enderite-CJ-fabric-mc-1.21-2.2.1. The mod Gilded Netherite CJ Edition is installed to.
![Capture d'écran 2024-06-23 000024](https://github.com/Craftjakob/Enderite-CJ-Edition/assets/103371268/6c3f158f-83e2-487c-abe6-607e525674d2)
![image](https://github.com/Craftjakob/Enderite-CJ-Edition/assets/103371268/c279b0ae-760c-4f50-bd5f-58411940939b)
![image](https://github.com/Craftjakob/Enderite-CJ-Edition/assets/103371268/0dcd42d8-ab20-49b6-b2a5-2f96a208ef4b)

**Comment by Craftjakob** [comment]
Yes I have removed the tags from Gilded Netherite, I have added them back, so it is now fixed, thanks for the report.
I am going to upload the fixed version now.

**Comment by Joaofixe** [comment]
Is the second craft supposed to work? I'm trying to transform an Enderite Chestplate into a Gilded Enderite Chestplate, but it's not working.
The craft to transform a Gilded Netherite Chestplate into an Gilded Enderite Chestplate is working,

![image](https://github.com/Craftjakob/Enderite-CJ-Edition/assets/95045402/8a0f8959-18d9-47d0-a2a5-d170abc09e98)

**Comment by Craftjakob** [comment]
Now it is too late, to morrow I going to fix the Tag issue again.

**Comment by Craftjakob** [comment]
I published another update earlier.
Now it should be fixed.
