### ISSUE TITLE
The name of the mod incorrectly appears when it shows up in mod mismatch warning.

### ISSUE THREAD

**Issue by zvn570** [Craftjakob/Enderite-CJ-Edition#15]
![image](https://github.com/user-attachments/assets/b8f317bc-be16-491a-b5dd-f02b3a73c73c)

**Comment by Craftjakob** [comment]
Thank you for the report, but that is not my problem.

I have never named my Mod Blaze Powder In End Cities, it can be Config API, because I copied over a lot things from there, but a name wich is not one of my projects and is in version 1.0.0 is not possible.
