### ISSUE TITLE
RE: Enderite Ore not minable in 1.1.1

### ISSUE THREAD

**Issue by CherryBella** [Craftjakob/Enderite-CJ-Edition#2]
This mod is great, but I found there is no way for me to get raw enderite as even with a netherite or enderite pickaxe, the enderite ore would just break into nothing. The only way I've found to get around this is to Silk Touch the ore, which drops the ore block and then you can smelt it into scraps. But considering that isn't the real way to get enderite, I'm guessing something is bugged.

**Comment by Craftjakob** [comment]
Ok, wait

**Comment by Craftjakob** [comment]
All loot tables do not work. Wow
Datagen for Block loot tables working nice

**Comment by Craftjakob** [comment]
So I fixed it, you need to wait a few minutes.
And yes, it was a bug.

Thank you very much for your feedback!

**Comment by CherryBella** [comment]
No problem, and thank you so much for fixing it!
