### ISSUE TITLE
Server crashes when player with enderite armour goes near endermite that's spawned in structures in the nether

### ISSUE THREAD

**Issue by ajaseem129** [Craftjakob/Enderite-CJ-Edition#3]
Love the mod but there's a persistent crash issue on our server which is a custom modpack with a variety of structure mods as well as this. 
We just got to the end and during our explorations we've encountered multiple crashes, all of which had one thing in common which was the enderite armour set and endermite. 
Some assistance to fix this would go a long way!!!
Crash report has been attached below, please let me know how we can fix this issue

[crash-2023-08-01_15.57.20-server.txt](https://github.com/Craftjakob/Enderite-CJ-Edition/files/12231679/crash-2023-08-01_15.57.20-server.txt)

**Comment by Craftjakob** [comment]
Is that in the 1.19?

**Comment by Craftjakob** [comment]
A maybe easy fix is to disable endermites are peaceful full set bonus. But that is not an elegant way.
I need to make tests and then to try to get a solution.

But can you give some more information?:
Which minecraft version? = 1.20.1
Which Forge version? = 47.1.43
Which enderite version? = 1.3.0
How do you do, that you get the crash?
- You say that you have a full set of enderite on?

**Comment by Craftjakob** [comment]
Is that now every time when you start the server, or if you join the server with the full set of enderite?

**Comment by ajaseem129** [comment]
Minecraft Version = 1.20.1
Forge version = 47.1.43
Enderite version = 1.30

When one of my friends who had a full set of enderite armour landed at a structure that had endermite spawning in it.
We tried disabling the set effect but that didn't help.
This happens only in some places through the end so the crashes are usually abrupt and I've to admin tp the player to another location to play peacefully.
Is there any other info we can provide apart from the crash report attached above?

**Comment by abdultradebrains** [comment]
Alright. I think we'll have to disable this mod, Il make sure to look into the other mods conflicting. We'll wait for your next update. Hope to hear about that soon!!

**Comment by Craftjakob** [comment]
I released just now the 1.3.2 update where this bug should be fixed. Because ArmorUtils called a Local player method and not for both. That's now solved and also the 1.19 should be fixed. In my test, everything was fine. No Problems nothing!

Thank you for your report and your support!!!

**Comment by Craftjakob** [comment]
The new uploading system from Curseforge to protect you for Malware is a little slow, but the files are uploaded you can later download that! I mark this as closed. If you have this problem again, reopen it or made a new issue.
Thank you!

**Comment by Craftjakob** [comment]
It is now really fixed with the 1.3.3
