### ISSUE TITLE
ender amethyst texture issue 1.20.1

### ISSUE THREAD

**Issue by sharkyman123** [Craftjakob/Enderite-CJ-Edition#6]
The **ender amethyst texture has a cyan background** instead of air, looks weird plz fix RIGHT NOW (btw its in 1.20.1 do that one plz ok?)

**Comment by Craftjakob** [comment]
It's not a cyan background it's black, but yes it is true, because I forgot to register the Client in the fabric.mod.json

In the next update is will be fixed.

And please do not say RIGHT NOW.

But thanks for the report!
