### ISSUE TITLE
[Forge 1.20.1] Invalid tags requested in recipes (and some config requests)

### ISSUE THREAD

**Issue by vizthex123** [Craftjakob/Enderite-CJ-Edition#8]
I noticed that all of the Gilded variants ask for items tagged with `forge;materials/golden_core`, but nothing has that tag (also, it should be a custom `enderite:golden_core` tag).

Same for the duplicate recipes that want items tagged with `forge:tools/gilded_netherite_axe`. Seem that one's there for mod compat (I know Additional Additions has gilded netherite gear), but those recipes shouldn't load in if the tag is empty.

In addition, it'd be nice to have a config option that lets us disable the "technical" tooltips (e.g. how to enable cracked ore and configure walking speed bonuses for the boots)

**Comment by Craftjakob** [comment]
You can configure almost everything inside the configs.
In Forge or NeoForge you can open the Config Screen in the main menu or if you are in 1.20.3+ you can open it also in game. You only need to open the Mods Screen, by pressing the mods button.

Or you can open your game folder and open the config folder, inside this folder you can open the config files for Enderite, there is a client and a common file for Enderite, inside the client one you can disable tooltips and inside the common one you can change Tools Stats, disable effects and a lot of more things.

You can actually disable every effect inside this config. The Config Screen is the same as the config file, but it is inside the game and much more organized.

**Comment by Craftjakob** [comment]
Here are some pictures how you can access the Config in game.
![image](https://github.com/Craftjakob/Enderite-CJ-Edition/assets/107345776/1341d584-94cb-460d-b17d-fddd6233e7c2)
![image](https://github.com/Craftjakob/Enderite-CJ-Edition/assets/107345776/bec2f9ee-2007-4538-8a56-4b0d388ac337)
![image](https://github.com/Craftjakob/Enderite-CJ-Edition/assets/107345776/7d361328-5b0f-4d7b-bae8-140a372dff8f)
![image](https://github.com/Craftjakob/Enderite-CJ-Edition/assets/107345776/3045e62e-8076-4a66-baf9-502c383e6515)

**Comment by Craftjakob** [comment]
The Recipes, yes it is for a compat for Gilded Netherite CJ Edition. And yes, I can try to load these recipes only if the tag is not empty.

**Comment by vizthex123** [comment]
> You can configure almost everything inside the configs. In Forge or NeoForge you can open the Config Screen in the main menu or if you are in 1.20.3+ you can open it also in game. You only need to open the Mods Screen, by pressing the mods button.
> 
> Or you can open your game folder and open the config folder, inside this folder you can open the config files for Enderite, there is a client and a common file for Enderite, inside the client one you can disable tooltips and inside the common one you can change Tools Stats, disable effects and a lot of more things.
> 
> You can actually disable every effect inside this config. The Config Screen is the same as the config file, but it is inside the game and much more organized.

yes, i checked those before posting this but couldn't find anything to disable the recipes requesting invalid tags.

disabling tooltips reads as "there's no tooltips at all" to me, rather than "only remove tooltips explaining how to configure the mod".

**Comment by vizthex123** [comment]
> The Recipes, yes it is for a compat for Gilded Netherite CJ Edition. And yes, I can try to load these recipes only if the tag is not empty.

yeah, that'd be nice. I manually tagged a few gold items too, so perhaps the mod could tag Gold Ingots or something if the Gilded Netherite mod isn't installed?

**Comment by Craftjakob** [comment]
Hmm...
I don't know, because the Gilded Enderite Armor and Tools is only because of Gilded Netherite and the Golden Core, that you require for crafting.
I don't think, that I will do it that way.

If you press shift over a Gilded Enderite Item, then is says, that you need to have Gilded Netherite installed.

**Comment by Craftjakob** [comment]
> > You can configure almost everything inside the configs. In Forge or NeoForge you can open the Config Screen in the main menu or if you are in 1.20.3+ you can open it also in game. You only need to open the Mods Screen, by pressing the mods button.
> > 
> > Or you can open your game folder and open the config folder, inside this folder you can open the config files for Enderite, there is a client and a common file for Enderite, inside the client one you can disable tooltips and inside the common one you can change Tools Stats, disable effects and a lot of more things.
> > 
> > You can actually disable every effect inside this config. The Config Screen is the same as the config file, but it is inside the game and much more organized.
> 
> yes, i checked those before posting this but couldn't find anything to disable the recipes requesting invalid tags. Did it manually for now, but I wanted to report it since it warrants a report imo.
> 
> disabling tooltips reads as "there's no tooltips at all" to me, rather than "only remove tooltips explaining how to configure the mod".

Could you explain that again? I don't understand it 100% correctly.
And If I understand your problem, and it is a bug or a thing to add, then I will let you tell tomorrow.

**Comment by vizthex123** [comment]
> > > You can configure almost everything inside the configs. In Forge or NeoForge you can open the Config Screen in the main menu or if you are in 1.20.3+ you can open it also in game. You only need to open the Mods Screen, by pressing the mods button.
> > > Or you can open your game folder and open the config folder, inside this folder you can open the config files for Enderite, there is a client and a common file for Enderite, inside the client one you can disable tooltips and inside the common one you can change Tools Stats, disable effects and a lot of more things.
> > > You can actually disable every effect inside this config. The Config Screen is the same as the config file, but it is inside the game and much more organized.
> > 
> > 
> > yes, i checked those before posting this but couldn't find anything to disable the recipes requesting invalid tags. Did it manually for now, but I wanted to report it since it warrants a report imo.
> > disabling tooltips reads as "there's no tooltips at all" to me, rather than "only remove tooltips explaining how to configure the mod".
> 
> Could you explain that again? I don't understand it 100% correctly. And If I understand your problem, and it is a bug or a thing to add, then I will let you tell tomorrow.

I just misread it, that's all.

As for tags, having a tooltip should be in conjunction with recipes being disabled. There's no need to add in non-functional recipes if the mod that adds the items it requires isn't installed.

**Comment by Craftjakob** [comment]
I'm closing this issue, because I don't know 100% what you mean, and that want I understand is not possible or made no sens, because I can not check if a mod is loaded and then a recipe is enabled, there is a way with conditions, but only for NeoForge and Forge. 
And If I'm going to add these recipes to the compat mod, then the compat mod adds recipes, which are "invalid".

In my newest version of Enderite for 1.20.5+ are all tags, recipes and code related things change, maybe that is what you want.

If not, then please reopen this issue or create a new one and say exactly what you want.

**Comment by vizthex123** [comment]
Well, I explained it already - but it's fine.

Like I said, it's not a big deal. Just a bit annoying if you only have this mod loaded.

**Comment by Craftjakob** [comment]
That the recipes are loaded?

**Comment by Craftjakob** [comment]
How would you load the recipes?
